# Generated by Django 4.2 on 2023-07-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_grade', models.CharField(max_length=1)),
                ('scgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('batchCode', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Semester Data',
            },
        ),
    ]
