# Generated by Django 4.2.4 on 2023-08-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCode',
            fields=[
                ('batchCode', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('total_credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_grade', models.CharField(max_length=1)),
                ('scgpa', models.DecimalField(decimal_places=6, max_digits=8)),
                ('honorsDept', models.CharField(max_length=5, null=True)),
                ('minorsDept', models.CharField(max_length=5, null=True)),
                ('batchCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminControl.batchcode')),
            ],
            options={
                'verbose_name_plural': 'Semester Data',
            },
        ),
        migrations.CreateModel(
            name='MinorsModel',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseChoice1', models.CharField(default=None, max_length=5, null=True)),
                ('courseChoice2', models.CharField(default=None, max_length=5, null=True)),
                ('scgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('selectedDept', models.CharField(default=None, max_length=5, null=True)),
                ('batchCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminControl.batchcode')),
            ],
            options={
                'verbose_name_plural': 'Minors Applied Data',
            },
        ),
        migrations.CreateModel(
            name='HonorsModel',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=5)),
                ('scgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('selectedDept', models.CharField(default=None, max_length=5, null=True)),
                ('batchCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminControl.batchcode')),
            ],
            options={
                'verbose_name_plural': 'Honors Applied Data',
            },
        ),
    ]
