# Generated by Django 4.2 on 2023-05-08 23:13

from django.db import migrations, models


def create_initial_depts(apps, schema_editor):
    dept = apps.get_model('AdminControl', 'Department')
    depts = [
        {'dept_id': '1', 'dept_name': 'CIVIL ENGINEERING'},
        {'dept_id': '2', 'dept_name': 'Electrical & Electronics Engineering'},
        {'dept_id': '3', 'dept_name': 'Mechanical Engineering'},
        {'dept_id': '4', 'dept_name': 'Electronics and Communication Engineering'},
        {'dept_id': '5', 'dept_name': 'Computer Science Engineering'},
        {'dept_id': '12', 'dept_name': 'Information Technology'},
        {'dept_id': '31', 'dept_name': 'Metallurgical Engineering'},
    ]

    for country_data in depts:
        dept.objects.create(**country_data)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(
                    max_length=5, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('rollno', models.CharField(max_length=10,
                 primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('total_credits', models.DecimalField(
                    decimal_places=2, max_digits=5)),
                ('total_grade', models.CharField(max_length=1)),
                ('scgpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'Semester Data',
            },
        ),
        migrations.RunPython(create_initial_depts),
    ]
