# Generated by Django 4.2 on 2023-07-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminControl', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
