# Generated by Django 4.2 on 2023-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorsModel',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=5)),
                ('scgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('selectedDept', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='honorsDept',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='minorsDept',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
