# Generated by Django 4.2.4 on 2023-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminControl', '0002_alter_userdata_batchcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='honorsDept',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='minorsDept',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
