# Generated by Django 4.2 on 2023-07-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminControl', '0002_honorsmodel_userdata_honorsdept_userdata_minorsdept'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinorsModel',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('courseChoice1', models.CharField(max_length=5)),
                ('courseChoice2', models.CharField(max_length=5)),
                ('scgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('selectedDept', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Minors Applied Data',
            },
        ),
        migrations.AlterModelOptions(
            name='honorsmodel',
            options={'verbose_name_plural': 'Honors Applied Data'},
        ),
    ]
