# Generated by Django 4.2 on 2023-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminControl', '0003_minorsmodel_alter_honorsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorsmodel',
            name='selectedDept',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='minorsmodel',
            name='courseChoice1',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='minorsmodel',
            name='courseChoice2',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
