# Generated by Django 4.2.4 on 2023-08-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminControl', '0003_alter_userdata_honorsdept_alter_userdata_minorsdept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorsmodel',
            name='batchCode',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='minorsmodel',
            name='batchCode',
            field=models.CharField(max_length=9),
        ),
    ]
