# Generated by Django 4.2 on 2023-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminControl', '0004_alter_honorsmodel_selecteddept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorsmodel',
            name='selectedDept',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
