# Generated by Django 4.2.2 on 2023-09-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminControl', '0004_alter_honorsmodel_batchcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorsmodel',
            name='waiting_list',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='minorsmodel',
            name='courseChoice3',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='minorsmodel',
            name='waiting_list1',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='minorsmodel',
            name='waiting_list2',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='minorsmodel',
            name='waiting_list3',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
