# Generated by Django 4.2.2 on 2023-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminControl', '0009_rename_waiting_list_minorsmodel_waiting_list1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorsmodel',
            name='waiting_list',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
